### ISSUE TITLE
Adaptar vista de admin 

### ISSUE THREAD

**Issue by D4v1d98Ru1z** [OdontologyTeam/Front-end-APP#3]
## Issue para marcar ( [x] cuando esté completado)
- [x] Remover el botón Upgrade pro
- [x]  Cambiar los nombres en la side bar
- [x] Cambiar idioma de los componentes trabajados.
- [x] ¿Qué paquete de iconos se están usando dentro del proyecto?

**Comment by teamzz111** [comment]
Icon pack


![image](https://user-images.githubusercontent.com/37392536/55648430-e84b9a80-57a5-11e9-9093-a640c2fad98f.png)
